{% set version = '0.7.6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dplyr
  version: {{ version|replace("-", "_") }}

source:
  fn: dplyr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/dplyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dplyr/dplyr_{{ version }}.tar.gz
  sha256: d489cc8b53854ec30737bb7d39b331b67ca35f4275ad19e97420d7a247808330

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]
  host:
    - r-base
    - r-bh >=1.58.0_1
    - r-r6 >=2.2.2
    - r-rcpp >=0.12.15
    - r-assertthat >=0.2.0
    - r-bindrcpp >=0.2.0.9000
    - r-glue >=1.1.1
    - r-magrittr >=1.5
    - r-pkgconfig >=2.0.1
    - r-plogr >=0.1.10
    - r-rlang >=0.2.0
    - r-tibble >=1.3.1
    - r-tidyselect >=0.2.3
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-bh >=1.58.0_1
    - r-r6 >=2.2.2
    - r-rcpp >=0.12.15
    - r-assertthat >=0.2.0
    - r-bindrcpp >=0.2.0.9000
    - r-glue >=1.1.1
    - r-magrittr >=1.5
    - r-pkgconfig >=2.0.1
    - r-plogr >=0.1.10
    - r-rlang >=0.2.0
    - r-tibble >=1.3.1
    - r-tidyselect >=0.2.3

test:
  commands:
    - $R -e "library('dplyr')"           # [not win]
    - "\"%R%\" -e \"library('dplyr')\""  # [win]

about:
  home: http://dplyr.tidyverse.org, https://github.com/tidyverse/dplyr
  license: MIT
  summary: A fast, consistent tool for working with data frame like objects, both in memory and
    out of memory.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
