{% set version = '1.0.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dplyr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dplyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dplyr/dplyr_{{ version }}.tar.gz
  sha256: bfb65131cd24d891e671999be29e6dfebb3eefa41c262dbc7a13d7c0ff3db1f3

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-ellipsis
    - r-generics
    - r-glue >=1.3.2
    - r-lifecycle >=0.2.0
    - r-magrittr >=1.5
    - r-rlang >=0.4.6
    - r-tibble >=2.1.3
    - r-tidyselect >=1.1.0
    - r-vctrs >=0.3.0
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-r6
    - r-ellipsis
    - r-generics
    - r-glue >=1.3.2
    - r-lifecycle >=0.2.0
    - r-magrittr >=1.5
    - r-rlang >=0.4.6
    - r-tibble >=2.1.3
    - r-tidyselect >=1.1.0
    - r-vctrs >=0.3.0

test:
  commands:
    - $R -e "library('dplyr')"           # [not win]
    - "\"%R%\" -e \"library('dplyr')\""  # [win]

about:
  home: https://dplyr.tidyverse.org, https://github.com/tidyverse/dplyr
  license: MIT
  summary: A fast, consistent tool for working with data frame like objects, both in memory and
    out of memory.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Type: Package
# Package: dplyr
# Title: A Grammar of Data Manipulation
# Version: 1.0.0
# Authors@R: c(person(given = "Hadley", family = "Wickham", role = c("aut", "cre"), email = "hadley@rstudio.com", comment = c(ORCID = "0000-0003-4757-117X")), person(given = "Romain", family = "Francois", role = "aut", comment = c(ORCID = "0000-0002-2444-4226")), person(given = "Lionel", family = "Henry", role = "aut"), person(given = "Kirill", family = "Muller", role = "aut", comment = c(ORCID = "0000-0002-1416-3412")), person(given = "RStudio", role = c("cph", "fnd")))
# Description: A fast, consistent tool for working with data frame like objects, both in memory and out of memory.
# License: MIT + file LICENSE
# URL: https://dplyr.tidyverse.org, https://github.com/tidyverse/dplyr
# BugReports: https://github.com/tidyverse/dplyr/issues
# Depends: R (>= 3.2.0)
# Imports: ellipsis, generics, glue (>= 1.3.2), lifecycle (>= 0.2.0), magrittr (>= 1.5), methods, R6, rlang (>= 0.4.6), tibble (>= 2.1.3), tidyselect (>= 1.1.0), utils, vctrs (>= 0.3.0)
# Suggests: bench, broom, callr, covr, DBI, dbplyr (>= 1.4.3), knitr, Lahman, lobstr, microbenchmark, nycflights13, purrr, rmarkdown, RMySQL, RPostgreSQL, RSQLite, testthat (>= 2.1.0), withr
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: yes
# RoxygenNote: 7.1.0
# NeedsCompilation: yes
# Packaged: 2020-05-28 23:53:24 UTC; hadley
# Author: Hadley Wickham [aut, cre] (<https://orcid.org/0000-0003-4757-117X>), Romain Francois [aut] (<https://orcid.org/0000-0002-2444-4226>), Lionel Henry [aut], Kirill Muller [aut] (<https://orcid.org/0000-0002-1416-3412>), RStudio [cph, fnd]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2020-05-29 15:00:03 UTC
