{% set version = '0.8.0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dplyr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dplyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dplyr/dplyr_{{ version }}.tar.gz
  sha256: 8408889d31a32527dbd846b3a6d995a2a7db7a51618ff28e61747afcb25ccd5c

build:
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-bh >=1.58.0_1
    - r-r6 >=2.2.2
    - r-rcpp >=1.0.0
    - r-assertthat >=0.2.0
    - r-glue >=1.1.1
    - r-magrittr >=1.5
    - r-pkgconfig >=2.0.1
    - r-plogr >=0.1.10
    - r-rlang >=0.3.0
    - r-tibble >=2.0.0
    - r-tidyselect >=0.2.5
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-bh >=1.58.0_1
    - r-r6 >=2.2.2
    - r-rcpp >=1.0.0
    - r-assertthat >=0.2.0
    - r-glue >=1.1.1
    - r-magrittr >=1.5
    - r-pkgconfig >=2.0.1
    - r-plogr >=0.1.10
    - r-rlang >=0.3.0
    - r-tibble >=2.0.0
    - r-tidyselect >=0.2.5

test:
  commands:
    - $R -e "library('dplyr')"           # [not win]
    - "\"%R%\" -e \"library('dplyr')\""  # [win]

about:
  home: http://dplyr.tidyverse.org, https://github.com/tidyverse/dplyr
  license: MIT
  summary: A fast, consistent tool for working with data frame like objects, both in memory and
    out of memory.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Type: Package
# Package: dplyr
# Title: A Grammar of Data Manipulation
# Version: 0.8.0.1
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", c("aut", "cre"), comment = c(ORCID = "0000-0003-4757-117X")), person("Romain", "Fran\u00e7ois", role = "aut", comment = c(ORCID = "0000-0002-2444-4226")), person("Lionel", "Henry", role = "aut"), person("Kirill", "M\u00fcller", role = "aut", comment = c(ORCID = "0000-0002-1416-3412")), person("RStudio", role = c("cph", "fnd")) )
# Description: A fast, consistent tool for working with data frame like objects, both in memory and out of memory.
# License: MIT + file LICENSE
# URL: http://dplyr.tidyverse.org, https://github.com/tidyverse/dplyr
# BugReports: https://github.com/tidyverse/dplyr/issues
# Depends: R (>= 3.1.2)
# Imports: assertthat (>= 0.2.0), glue (>= 1.1.1), magrittr (>= 1.5), methods, pkgconfig (>= 2.0.1), R6 (>= 2.2.2), Rcpp (>= 1.0.0), rlang (>= 0.3.0), tibble (>= 2.0.0), tidyselect (>= 0.2.5), utils
# Suggests: bit64 (>= 0.9.7), callr (>= 3.1.1), covr (>= 3.0.1), DBI (>= 0.7.14), dbplyr (>= 1.2.0), dtplyr (>= 0.0.2), ggplot2 (>= 2.2.1), hms (>= 0.4.1), knitr (>= 1.19), Lahman (>= 3.0-1), lubridate (>= 1.7.4), MASS, mgcv (>= 1.8.23), microbenchmark (>= 1.4.4), nycflights13 (>= 0.2.2), rmarkdown (>= 1.8), RMySQL (>= 0.10.13), RPostgreSQL (>= 0.6.2), RSQLite (>= 2.0), testthat (>= 2.0.0), withr (>= 2.1.1), broom (>= 0.5.1), purrr (>= 0.3.0), readr (>= 1.3.1), crayon (>= 1.3.4)
# LinkingTo: BH (>= 1.58.0-1), plogr (>= 0.1.10), Rcpp (>= 1.0.0)
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: yes
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-02-15 15:12:47 UTC; ripley
# Author: Hadley Wickham [aut, cre] (<https://orcid.org/0000-0003-4757-117X>), Romain Francois [aut] (<https://orcid.org/0000-0002-2444-4226>), Lionel Henry [aut], Kirill Muller [aut] (<https://orcid.org/0000-0002-1416-3412>), RStudio [cph, fnd]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-02-15 15:30:53 UTC
