# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fMcmzYiYeAtjrpfMaV+dD+nrHJs7YaBNbriIRuGWnHxZLnA+pi9oWyYOT+CtA74fhYMQjFrQnG3k0/S3BhC44UwttCleNhJSHMJw8wLmnIN2yJT17YGVRO1WbCnk4SQFrcsZwVbodkKpQHrDfFLVhNe6U+oCLYIer9bFTq+C8ah4K40iL184IeyQWE61VF4c2BIpws4e+iZfxlx6XxXUh1fhy0+LGND6SIYMBnviff0QLca7j61nTGbSRc13a125l47+PLQabKomYGsKoNS0Px0MafeoHvjw73lcMXslF7eARfAfb7+gjTUhfCi6flhIUQ4gY//qIOruu+Xv3mxcr7RuGqbGauOj45+9bOTICn6x6d+VRR4+PX13nIYffPcTcokPRE9ant6Gjg4krwJ7INtYm/zWWVMqF6oOCJzOAMIsB/9QiDyjn9Ri7RB2L4tAeHqlI7neDwl2qJUVE26b0oK07zC2OTUe+nMjLus4CY8nCYCY8qQTLZ+J1ZVX0i6RqYCKCSfhMgqrVCcjRbaXqvtMp4Zhj/E+bxeVt4K5A/mFE2eKEriCRF5urHu8lGMnu7SQYvLIKkrI7VuNekQ+KUS97keyF9w4qN1Fd5hX38rTFAio35D+rXeIUwWpC40OyNEAI8qksCb+BUFID/9DucYYxYo4ABAhUXCx6/8GhtY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
